### ISSUE TITLE
`nightly-main` hasn't updated recently

### ISSUE THREAD

**Issue by calda** [SwiftFiddle/swiftfiddle-runner#75]
I noticed `nightly-main` hasn't updated recently. 

Is SwiftFiddle using [this](https://hub.docker.com/layers/swift/swiftlang/swift/nightly-main/images/sha256-636a42df6785d6b069f453ec848f2cd9d54a879edfda54d924dd69d775c9c87f?context=explore) docker image? It says it hasn't been updated in three months. I wonder if this is an outdated reference, or if its build pipeline is broken.

**Comment by kishikawakatsumi** [comment]
Thank you for reporting. `nightly-main-bionic` tag seems no longer maintained. I use `nighly-main-focal` instead. https://github.com/SwiftFiddle/swiftfiddle-runner/commit/112614ff446d1ee6595622ca0f442a291cac315d

Could you check if it is fixed?

I didn't notice, thank you. @calda

**Comment by calda** [comment]
Working now, thanks!
